# Mire de resolution spatiale pour l'imagerie. Contient 6 serie de plaques paralelles qu'on souhaite pouvoir
# differentier l'une de l'autre. Leur distance varie d'une serie a l'autre.

#####################
# Material Cylinder #
#####################

/gate/world/daughters/name materialCylinder
/gate/world/daughters/insert cylinder
/gate/materialCylinder/geometry/setRmin 0. mm
/gate/materialCylinder/geometry/setRmax 12 mm
/gate/materialCylinder/geometry/setHeight 20 mm
/gate/materialCylinder/placement/setRotationAxis 1 0 0
/gate/materialCylinder/placement/setRotationAngle 90. deg
/gate/materialCylinder/setMaterial Water
/gate/materialCylinder/vis/forceWireframe
/gate/materialCylinder/vis/setColor cyan
/gate/materialCylinder/attachPhantomSD

##########
# Panel 1#
##########
/gate/materialCylinder/daughters/name panel1
/gate/materialCylinder/daughters/insert box
/gate/panel1/placement/setTranslation 4 -6.9282 0 mm
/gate/panel1/geometry/setXLength 7 mm
/gate/panel1/geometry/setYLength 0.2 mm
/gate/panel1/geometry/setZLength 3 mm
/gate/panel1/placement/setRotationAxis 1 0 0
/gate/panel1/setMaterial SpineBone
/gate/panel1/vis/setColor green
/gate/panel1/attachPhantomSD
/gate/panel1/vis/forceSolid

/gate/panel1/repeaters/insert linear
/gate/panel1/linear/setRepeatNumber 10
/gate/panel1/linear/setRepeatVector 2.5 0 0 mm
/gate/panel1/linear/autoCenter true

##########
# Panel 2#
##########
/gate/materialCylinder/daughters/name panel2
/gate/materialCylinder/daughters/insert box
/gate/panel2/placement/setTranslation 8 0 0 mm
/gate/panel2/geometry/setXLength 20 mm
/gate/panel2/geometry/setYLength 3 mm
/gate/panel2/geometry/setZLength 0.08 mm
/gate/panel2/placement/setRotationAxis 1 0 0
/gate/panel2/setMaterial SpineBone
/gate/panel2/vis/setColor yellow
/gate/panel2/attachPhantomSD
/gate/panel2/vis/forceSolid

/gate/panel2/repeaters/insert linear
/gate/panel2/linear/setRepeatNumber 10
/gate/panel2/linear/setRepeatVector 2 0 0 mm
/gate/panel2/linear/autoCenter true

##########
# Panel 3#
##########
/gate/materialCylinder/daughters/name panel3
/gate/materialCylinder/daughters/insert box
/gate/panel3/placement/setTranslation 4 6.9282 0 mm
/gate/panel3/geometry/setXLength 0.2 mm
/gate/panel3/geometry/setYLength 3 mm
/gate/panel3/geometry/setZLength 20 mm
/gate/panel3/placement/setRotationAxis 1 0 0
/gate/panel3/setMaterial SpineBone
/gate/panel3/vis/setColor white
/gate/panel3/attachPhantomSD
/gate/panel3/vis/forceSolid

/gate/panel3/repeaters/insert linear
/gate/panel3/linear/setRepeatNumber 10
/gate/panel3/linear/setRepeatVector 1.428 0 0 mm
/gate/panel3/linear/autoCenter true

##########
# Panel 4#
##########
/gate/materialCylinder/daughters/name panel4
/gate/materialCylinder/daughters/insert box
/gate/panel4/placement/setTranslation -4 6.9282 0 mm
/gate/panel4/geometry/setXLength 0.125 mm
/gate/panel4/geometry/setYLength 3 mm
/gate/panel4/geometry/setZLength 20 mm
/gate/panel4/placement/setRotationAxis 1 0 0
/gate/panel4/setMaterial SpineBone
/gate/panel4/vis/setColor red
/gate/panel4/attachPhantomSD
/gate/panel4/vis/forceSolid

/gate/panel4/repeaters/insert linear
/gate/panel4/linear/setRepeatNumber 10
/gate/panel4/linear/setRepeatVector 1.25 0 0 mm
/gate/panel4/linear/autoCenter true


##########
# Panel 6#
##########
/gate/materialCylinder/daughters/name panel6
/gate/materialCylinder/daughters/insert box
/gate/panel6/placement/setTranslation -4 -6.9282 0 mm
/gate/panel6/geometry/setXLength 0.08 mm
/gate/panel6/geometry/setYLength 3 mm
/gate/panel6/geometry/setZLength 20 mm
/gate/panel6/placement/setRotationAxis 1 0 0
/gate/panel6/setMaterial SpineBone
/gate/panel6/vis/setColor gray
/gate/panel6/attachPhantomSD
/gate/panel6/vis/forceSolid

/gate/panel6/repeaters/insert linear
/gate/panel6/linear/setRepeatNumber 10
/gate/panel6/linear/setRepeatVector 0.83333 0 0 mm
/gate/panel6/linear/autoCenter true

############
# Rotation #
############

/gate/materialCylinder/moves/insert rotation
/gate/materialCylinder/rotation/setSpeed 10. deg/s
/gate/materialCylinder/rotation/setAxis 0 0 1
