
# ============================
# == actor              ==
# ============================
/gate/output/fastanalysis/enable
/gate/actor/addActor  SPAD               main_actor
/gate/actor/main_actor/attachTo                         pixel
/gate/actor/main_actor/SPAD_config/ConfigPath        /app/dsas/GateDSAS/source/externals/flatSPAD/config/example.cfg
/gate/actor/main_actor/SPAD_config/ExportPath       /app/dsas/GateDSAS/examples/DSAS/output_sean.root
#/gate/actor/main_actor/SPAD_config/LocalMode true
#/gate/actor/main_actor/SPAD_config/LocalModeLength 87

