# Generate materials from Hounsfield units
/gate/HounsfieldMaterialGenerator/SetMaterialTable                  macro/phantom/Schneider2000MaterialsTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTable                   macro/phantom/Schneider2000DensitiesTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTolerance               1 g/cm3
/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename macro/phantom/phantom-HUmaterials.db
/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename       macro/phantom/phantom-HU2mat.txt
/gate/HounsfieldMaterialGenerator/Generate

# Insert CT image
/gate/world/daughters/name                      phantom
/gate/world/daughters/insert                    ImageNestedParametrisedVolume
/gate/geometry/setMaterialDatabase              macro/phantom/phantom-HUmaterials.db
/gate/phantom/geometry/setHUToMaterialFile      macro/phantom/phantom-HU2mat.txt
/gate/phantom/geometry/setImage                 macro/phantom/phantom.mhd
/gate/phantom/placement/setTranslation 0 0 90 mm
/gate/phantom/placement/setRotationAxis 1 0 0
/gate/phantom/placement/setRotationAngle 90 deg
/gate/phantom/attachPhantomSD
/gate/phantom/vis/forceWireframe

