/gate/source/addSource                           Mysource pulsed
/gate/source/Mysource/setTimeHist energy.txt
/gate/source/Mysource/setFrequency 50000000 Hz

/gate/source/Mysource/gps/verbose 2
/gate/source/Mysource/gps/particle               gamma
/gate/source/Mysource/gps/energytype             Arb
/gate/source/Mysource/gps/type					 Volume
/gate/source/Mysource/gps/shape			     	 Sphere
/gate/source/Mysource/gps/radius				 0.01 mm
/gate/source/Mysource/setActivity 				 2000. becquerel
/gate/source/Mysource/gps/energy             80 keV
/gate/source/Mysource/gps/direction              0. 0. -1.
/gate/source/Mysource/gps/centre                 0. 0 120 mm
/gate/source/Mysource/gps/angtype iso
/gate/source/Mysource/gps/mintheta 0. deg
/gate/source/Mysource/gps/maxtheta 8.2 deg
/gate/source/Mysource/gps/minphi 0. deg
/gate/source/Mysource/gps/maxphi 360. deg
/gate/source/list
